### ISSUE TITLE
Investigate: Ariadne Misuses W5100 and W5200

### ISSUE THREAD

**Issue by phillipjohnston** [embeddedartistry/athena-bootloader#19]
From original project:

From @davidhaenggi on February 9, 2015 14:40
Hi
I downloaded the Ariadne-Bootloader to use it with a OpenMediaController.
It's based on a Atmega2560 and includes a Wiznet W5100 ethernet chip.
In general the bootloader works great, thanks for the nice work.
While trying to upload bigger firmware files I was running into the "64-Package" Problem.
For me it looks like the arduino is receiving a completely messed up message instead of package number 64. When it tries to read the source IP address of the package it gets some random IP and therefor tries to send a response to this random IP. Thats why the Wiznet chip tries to reach to gateway, because the random IP is not in its IP range.
* The solution to set the gateway address to the same IP as the TFTP client was not satisfying to me, as I would like to send firmwares from different client-IPs.
* As a workaround I did some modification to the code:
1. Don't set return IP address and port if the message is not a valid tftp message. I moved the regarding code to the end of funtion processPacket() and add some validation check.
```
-  // Set up return IP address and port
    * uint8_t i;
    * for(i = 0; i < 6; i++) spiWriteReg(REG_S3_DIPR0 + i, buffer[i]);
+ // only set return address if paket received is wellformed, to avoid sending to random IP address.
    * if(returnCode != ERROR_INVALID && returnCode != ERROR_UNKNOWN){
    * // Set up return IP address and port
    * uint8_t i;
    * for(i = 0; i < 6; i++) spiWriteReg(REG_S3_DIPR0 + i, buffer[i]);
    * }
```
2. And I added the same validation check before sending any response messages in tftpPoll().
```
+ if(response != ERROR_INVALID && response != ERROR_UNKNOWN)
sendResponse(response);
```
Like this the arduino does not send any error for packet 64. The client repeats the packet and the transfer continues. With this changes I was able to set the TFTP_PACKET_DELAY to 0 and have a fast tftp transfer without any failures.
I know this is not a proper solution, but it works for me and I thought it may help someone.

**Comment by hagaigold** [comment]
> Currently, I don't have a W5100 (or W5200), so it has still not been tested

Tested with Mega+W5100.
This fix helps resolve issue #18 as well- when working properly with the WIZnet chip, we can decrease `TFTP_PACKET_DELAY`.

Attached are logs with the issue and without, after applying the suggested fix:
[Mego_w5100_bigimage_fail.txt](https://github.com/embeddedartistry/athena-bootloader/files/7912664/Mego_w5100_bigimage_fail.txt)
[Mego_w5100_bigimage_working.txt](https://github.com/embeddedartistry/athena-bootloader/files/7912665/Mego_w5100_bigimage_working.txt)

the issue is obvious if you follow the message `Processing packet of size nnnn`:

```
[2022-01-20 20:39:40.326] Tftp: Processing packet of size 0x8A0C
[2022-01-20 20:39:40.326] Tftp: Overflow
[2022-01-20 20:39:40.341] Tftp: Set up return address
[2022-01-20 20:39:40.341] Tftp: This is block 0x0002 with opcode 0x0003 and data length 0x0200
[2022-01-20 20:39:40.341] Tftp: Data block
[2022-01-20 20:39:40.341] Tftp: Writing data from address 0x000200
[2022-01-20 20:39:40.357] Tftp: Packet length adjusted to 0x0200
[2022-01-20 20:39:40.373] Tftp: Sent ACK
[2022-01-20 20:39:40.373] Tftp: Response sent
[2022-01-20 20:39:40.779] Tftp: Processing packet of size 0x8A0C
[2022-01-20 20:39:40.779] Tftp: Overflow
```
