### ISSUE TITLE
Add documentation about W5500 shield

### ISSUE THREAD

**Issue by hagaigold** [embeddedartistry/athena-bootloader#84]
Hi @phillipjohnston,

I just discovered that you maintaining this codebase, and the documentation you put here is very extensive.

Regarding an old discussion, we had in the previous project of this bootloader- https://github.com/loathingKernel/ariadne-bootloader/pull/38-
I would like to add that information about the different options to configure the SPI on the W5500 shield.
is it fitting here?

**Comment by phillipjohnston** [comment]
Hi @hagaigold,

Yes, that is welcome!

**Comment by phillipjohnston** [comment]
Also, it has been a long time so I don't recall whether I accounted for that or not in the fork... if you find that we need to handle some things differently to account for the shield options, we can get that fixed.

**Comment by hagaigold** [comment]
> if you find that we need to handle some things differently to account for the shield options, we can get that fixed.
not at all. I review a few shields boards and your fix is what has to be done.

Many first examples & tutorials use the "blink sketch" which does not work with shields that need SPI :(
Maybe the initial design want it there for signal communication, but if it is true, he had to put the LED on a different pin for the MEGA 🤷‍♂️

I wonder how many more people spend hours trying to blink the LED while pinging the shield-  so I just want to add some info about that.
