### ISSUE TITLE
Figure out new nightly CI strategy

### ISSUE THREAD

**Issue by phillipjohnston** [embeddedartistry/athena-bootloader#90]
Because the nightly build starts with a new tag, the build step will always generate new images (version number has changed), causing nightly builds to continually run even when there are no other changes. 

For now, this has been removed.

```
-    stage('Commit Updated Images')
-    {
-      steps
-      {
-
-        sh 'git checkout master'
-        sh 'git pull'
-        sh 'git commit -am "Updating firmware images with latest version number."'
-        sh 'git push'
-      }
-    }
```

**Comment by phillipjohnston** [comment]
Maybe we can put the smarts into the Makefile somehow.

**Comment by phillipjohnston** [comment]
Or a nightly_build.sh script.

**Comment by hagaigold** [comment]
> Or a nightly_build.sh script.

I am not familiar with how to propagate the result of the script to the Jenkins system (to stop or not the build stage), but below are two options to check against the git log.

Based on the last tag name, similar to what we have in the Makefile to extract the last version:
(this will work assuming there is  no `-` in the tag names)
```bash
#!/bin/bash

last_tag=$(git describe --long --dirty --tags)
tokens=(${last_tag//-/ })
number_of_commits_from_last_tag=${tokens[1]} 

#echo ${last_tag}
#echo ${number_of_commits_from_last_tag}

if [ ${number_of_commits_from_last_tag} -gt 0 ]
then
    echo 'do work'
else
    echo 'nothing to do...'
fi
```

Based on the last committer, if it is not `Embedded Artistry Buildbot`:
(this will work assuming Buildbot does not commit "something" that needs to trigger a new nightly build)

```bash
#!/bin/bash

if ! (git log -1 --pretty=format:'%an' | grep -iq buildbot)
then
    echo 'do work'
else
    echo 'nothing to do...'
fi
```

**Comment by phillipjohnston** [comment]
I agree, and I think with the work on being able to use the board manager will also obviate the need to clone (whereas before that wasn't an option)

**Comment by phillipjohnston** [comment]
I still needed to resolve this to address auto-generating the JSON file for each set of generated files. But this is now fixed - builds will abort if there have been no commits since the previous tag was created. Tags are created by the nightly build configuration after the JSON is committed.
